<?php

namespace Magenest\Movie\Model\Config\Backend;

use Magento\Framework\App\Config\ScopeConfigInterface;

class Relation extends \Magento\Framework\App\Config\Value
{
     protected $actorCollection;
     public function __construct(
         \Magento\Framework\Model\Context $context,
         \Magento\Framework\Registry $registry,
         ScopeConfigInterface $config,
         \Magento\Framework\App\Cache\TypeListInterface $cacheTypeList,
         \Magenest\Movie\Model\Resourcemodel\Actor\Collection $actorCollection,
         \Magento\Framework\Model\ResourceModel\AbstractResource $resource = null,
         \Magento\Framework\Data\Collection\AbstractDb $resourceCollection = null,
         array $data = []
     ) {
         $this->actorCollection = $actorCollection;
         parent::__construct($context, $registry, $config, $cacheTypeList, $resource, $resourceCollection, $data);
     }
     public function afterLoad()
     {
         $this->setValue($this-> actorCollection->countRecords());
         return parent::afterLoad(); // TODO: Change the autogenerated stub
     }
}