<div id="emipro-ko-example" data-bind="scope:'emipro-ko-example'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "emipro-ko-example": {
                        "component": "Magenest_DemoKnockout/js/kotemplate"
                        }
                    }
                }
            }
    }
    </script>
</div>
<h2 style="color: red">Hiển thị ngoài Knockout JS</h2>
