<h2>Reports Made Today</h2>
<table border="1" class="col-m-6 data-grid" style="width:500px;border-bottom:red;border-right: red;border-left: red;border-top: red;">
    <tr class="data-row">
        <td>All Module</td>
        <td><?php echo $block->getAllModule() ?></td>
    </tr>
    <tr class="data-row _odd-row">
        <td>Module you Install</td>
        <td><?php echo $block->getModuleInstall()?></td>
    </tr>

</table>
<style>
    .distances {
        margin-left: 50px;
        margin-right: 50px;
    }
</style>
<table class="distances">

</table>
<table border="1" class="col-m-6 data-grid" style="width:500px;border-bottom:red;border-right: red;border-left: red;border-top: red;">
    <tr class="data-row">
        <td>Customers</td>
        <td><?php echo $block->getNumberCustomer() ?></td>
    </tr>
    <tr class="data-row _odd-row">
        <td>Orders</td>
        <td><?php echo $block->getNumberOrder() ?></td>
    </tr>
    <tr class="data-row">
        <td>Products</td>
        <td><?php echo $block->getNumberProduct()?></td>
    </tr>
    <tr class="data-row _odd-row">
        <td>Invoices</td>
        <td><?php echo $block->getNumberInvoice() ?></td>
    </tr>
    <tr class="data-row">
        <td>Creditmemos</td>
        <td><?php echo $block->getNumberCreditmemo() ?></td>
    </tr>
</table>


