<h2>Reports Made Today</h2>
<table  class="col-m-6 data-grid" style="width:300px">
    <tr class="data-row">
        <td>All Module</td>
        <td><?php echo $block->getAllModule() ?></td>
    </tr>
    <tr class="data-row _odd-row">
        <td>Module you Install</td>
        <td><?php echo $block->getModuleInstall()?></td>
    </tr>

</table>
<style>
    .distances {
        margin-left: 50px;
        margin-right: 50px;
    }
</style>
<div class="distances">

</div>
<table border="1" class="col-m-6 data-grid" style="border-color: red">
    <tr class="data-row">
        <td>Customers</td>
        <td><?php echo $block->getNumberCustomer() ?></td>
    </tr>
    <tr class="data-row _odd-row">
        <td>Products</td>
        <td><?php echo $block->getNumberProduct()?></td>
    </tr>
    <tr class="data-row">
        <td>Invoices</td>
        <td><?php echo $block->getNumberInvoice() ?></td>
    </tr>
    <tr class="data-row _odd-row">
        <td>Creditmemos</td>
        <td><?php echo $block->getNumberCreditmemo() ?></td>
    </tr>
</table>


